server:
  port: 8081
spring:
  application:
    name: eureka-server
  devtools:
    restart:
      #热部署生效
      enabled: true
      #设置重启的目录
      additional-paths: eureka-server/src/main/java
      #classpath目录下的WEB-INF文件夹内容修改不重启
      exclude: WEB-INF/**
eureka:
  instance:
    hostname: eureka-server # eureka实例的主机名
  client:
    register-with-eureka: false # 不把自己注册到eureka上，如果要进行高可用就为true
    fetch-registry: false # 不从eureka上来获取服务的注册信息
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/