server:
  port: 8081
eureka:
  instance:
    hostname: eureka-server # eureka实例的主机名
  client:
    register-with-eureka: false # 不把自己注册到eureka上，如果要进行高可用就为true
    fetch-registry: false # 不从eureka上来获取服务的注册信息
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/