logging:
  config: classpath:logback-spring.xml
  path: D:/nmyslog/nmys

server:
  port: 8080

spring:
  application:
    name: springboot-api
  devtools:
    restart:
      #热部署生效
      enabled: true
      #设置重启的目录
      additional-paths: springboot-api/src/main/java
      #classpath目录下的WEB-INF文件夹内容修改不重启
      exclude: WEB-INF/**
  redis:
    host: 192.168.6.128
    port: 6379
eureka:
  instance:
    prefer-ip-address: true # 注册服务的时候使用服务的ip地址
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/